### ISSUE TITLE
Python bindings for libsdformat

### ISSUE THREAD

**Issue by azeey** [gazebosim/sdformat#931]
This issue is to keep track of tasks for creating python bindings for libsdformat. The goal is to create bindings only for the DOM classes in the library and provide a function to convert each class to an xml representation (in-memory or string). This will be used in an upcoming task to convert SDFormat files to MJCF.

- [x] Setup infrastructure for pybind11 in libsdformat. https://github.com/ignitionrobotics/sdformat/pull/932
- [ ] Create bindings for DOM classes
   - ## Priority 1:
      - ### Parsing
        - [x] Error https://github.com/ignitionrobotics/sdformat/pull/933
        - [x] ParserConfig https://github.com/ignitionrobotics/sdformat/pull/934
        - [ ] PrintConfig ?
      - ### Kinematics
        - [x] Frame https://github.com/ignitionrobotics/sdformat/pull/962
        - [x] Joint https://github.com/ignitionrobotics/sdformat/pull/961
          - [x] Add Sensor test https://github.com/gazebosim/sdformat/pull/1028
        - [x] JointAxis https://github.com/ignitionrobotics/sdformat/pull/960
        - [x] Link https://github.com/ignitionrobotics/sdformat/pull/952
           - [x] Add Sensor test https://github.com/gazebosim/sdformat/pull/1028
           - [x] Add Light test https://github.com/gazebosim/sdformat/pull/1013
           - [ ] Add ParticleEmitter test
        - [x] Model https://github.com/ignitionrobotics/sdformat/pull/963
          - [x]  Add Model tests
        - [x] Root https://github.com/ignitionrobotics/sdformat/pull/967
           - [x] Light https://github.com/gazebosim/sdformat/pull/1013
        - [x] SemanticPose
            - [x]  https://github.com/ignitionrobotics/sdformat/pull/951
            - [x] enable test (Link) https://github.com/ignitionrobotics/sdformat/pull/1001
        - [x] World https://github.com/ignitionrobotics/sdformat/pull/964
            - [ ] Add actor test?
            - [x] Add physics test
            - [x] Add light test https://github.com/gazebosim/sdformat/pull/1013
      - ### Geometry (collision and visual)
        - [x] Box https://github.com/ignitionrobotics/sdformat/pull/937
        - [x] Capsule https://github.com/ignitionrobotics/ign-math/pull/403 https://github.com/ignitionrobotics/sdformat/pull/944
        - [x] Collision https://github.com/ignitionrobotics/sdformat/pull/949
        - [x] Contact https://github.com/ignitionrobotics/sdformat/pull/940
        - [x] Cylinder https://github.com/ignitionrobotics/sdformat/pull/945
        - [x] Ellipsoid https://github.com/ignitionrobotics/sdformat/pull/946
        - [x] Geometry https://github.com/ignitionrobotics/sdformat/pull/947
        - [x] Material https://github.com/ignitionrobotics/sdformat/pull/948
           - [x] Pbr
        - [x] Mesh https://github.com/ignitionrobotics/sdformat/pull/942
        - [x] Plane https://github.com/ignitionrobotics/sdformat/pull/941
        - [x] Sphere https://github.com/ignitionrobotics/sdformat/pull/938
        - [x] Surface https://github.com/ignitionrobotics/sdformat/pull/940
        - [x] Visual https://github.com/ignitionrobotics/sdformat/pull/950
   - ## Priority 2:
      - ### Sensors
        - [x] Camera https://github.com/ignitionrobotics/sdformat/pull/982
        - [x] ForceTorque https://github.com/ignitionrobotics/sdformat/pull/983
        - [x] AirPressure https://github.com/ignitionrobotics/sdformat/pull/971
        - [x] Altimeter https://github.com/ignitionrobotics/sdformat/pull/970
        - [x] Atmosphere https://github.com/ignitionrobotics/sdformat/pull/968
        - [x] Imu https://github.com/ignitionrobotics/sdformat/pull/981
        - [x] Lidar https://github.com/ignitionrobotics/sdformat/pull/973
        - [x] Magnetometer https://github.com/ignitionrobotics/sdformat/pull/972
        - [x] NavSat https://github.com/ignitionrobotics/sdformat/pull/984
        - [x] Noise https://github.com/ignitionrobotics/sdformat/pull/969
        - [x] Sensor https://github.com/ignitionrobotics/sdformat/pull/988
      - ### Scene
        - [x] Light https://github.com/ignitionrobotics/sdformat/pull/989
        - [x] Scene https://github.com/ignitionrobotics/sdformat/pull/992
           - [x]  Add sky  
   - ## Priority 3:
      - ### Geometry (collision and visual)
        - [x] Heightmap, HeightmapBlend and HeightmapTexture https://github.com/ignitionrobotics/sdformat/pull/993
        - [x] Pbr and PbrWorkflow https://github.com/ignitionrobotics/sdformat/pull/994
   - ## Priority 4:
      - ### Simulator
        - [x] Gui https://github.com/ignitionrobotics/sdformat/pull/998
        - [x] Physics https://github.com/ignitionrobotics/sdformat/pull/995
        - [x] Plugin https://github.com/ignitionrobotics/sdformat/pull/997
        - [x] Sky https://github.com/ignitionrobotics/sdformat/pull/996
      - ### Scene
        - [x] ParticleEmitter https://github.com/ignitionrobotics/sdformat/pull/999
- [ ] Put python bindings in a separate cmake component
- [x] Use exceptions for error handling https://github.com/gazebosim/sdformat/pull/1061
- [ ] Add `ToElement` for each class the returns an xml representation (maybe `xml.etree.ElementTree`)

**Comment by ahcorde** [comment]
# TODOs

Some features were added in some other branches. I included here some TODOs to address them when these features will land on `main`

  - Polyline geometry
  - Include `shininess` in Material

**Comment by ahcorde** [comment]
we can consider this done. We should open small PR when a Python binding is missing
